//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterpartyToWeddingProject
    {
        public System.Guid CounterpartyId { get; set; }
        public System.Guid WeddingProjectId { get; set; }
        public string Summary { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> AlreadyPayed { get; set; }
    
        public virtual Counterparty Counterparty { get; set; }
        public virtual WeddingProject WeddingProject { get; set; }
    }
}
