//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toast
    {
        public Toast()
        {
            this.Visitors = new HashSet<Visitor>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid WeddingProjectId { get; set; }
        public int IndexNumber { get; set; }
        public string Description { get; set; }
    
        public virtual WeddingProject WeddingProject { get; set; }
        public virtual ICollection<Visitor> Visitors { get; set; }
    }
}
