//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public Visitor()
        {
            this.Toasts = new HashSet<Toast>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid WeddingProjectId { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public Nullable<int> VisitorBelongSideId { get; set; }
        public Nullable<int> VisitorRoleId { get; set; }
        public string Description { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    
        public virtual VisitorBelongSide VisitorBelongSide { get; set; }
        public virtual VisitorRole VisitorRole { get; set; }
        public virtual WeddingProject WeddingProject { get; set; }
        public virtual ICollection<Toast> Toasts { get; set; }
    }
}
