//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeddingProject
    {
        public WeddingProject()
        {
            this.CounterpartyToWeddingProjects = new HashSet<CounterpartyToWeddingProject>();
            this.Toasts = new HashSet<Toast>();
            this.Visitors = new HashSet<Visitor>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> PlannedDate { get; set; }
        public string Venue { get; set; }
    
        public virtual ICollection<CounterpartyToWeddingProject> CounterpartyToWeddingProjects { get; set; }
        public virtual ICollection<Toast> Toasts { get; set; }
        public virtual ICollection<Visitor> Visitors { get; set; }
    }
}
