//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeddingManagerDataContext : DbContext
    {
        public WeddingManagerDataContext()
            : base("name=WeddingManagerDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Counterparty> Counterparties { get; set; }
        public DbSet<CounterpartyRole> CounterpartyRoles { get; set; }
        public DbSet<CounterpartyToWeddingProject> CounterpartyToWeddingProjects { get; set; }
        public DbSet<Toast> Toasts { get; set; }
        public DbSet<Visitor> Visitors { get; set; }
        public DbSet<VisitorBelongSide> VisitorBelongSides { get; set; }
        public DbSet<VisitorRole> VisitorRoles { get; set; }
        public DbSet<WeddingProject> WeddingProjects { get; set; }
    }
}
